// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialButterfly.Data;

#nullable disable

namespace SocialButterfly.Data.SbMigrations
{
    [DbContext(typeof(SbContext))]
    [Migration("20260209161407_AddUserTypeKey")]
    partial class AddUserTypeKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("SocialButterfly.Data.SbSchema.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte[]>("Json")
                        .HasColumnType("BLOB")
                        .HasColumnName("json");

                    b.Property<DateTime?>("KeyCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("BLOB")
                        .HasColumnName("salt");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "users_name_ndx")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
